services:
  postgres:
    image: postgres:16
    container_name: nxtdev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - nxtdev_pgdata:/var/lib/postgresql/data

volumes:
  nxtdev_pgdata:

