-- Supabase SQL Editor schema for the nxtdev MVP (Prisma-compatible)
-- Notes:
-- - Uses quoted identifiers to match Prisma's default table/column casing.
-- - IDs are TEXT and are expected to be generated by the app (Prisma cuid()).

-- Enums
do $$ begin
  create type "UserRole" as enum ('user', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type "UserStatus" as enum ('active', 'suspended', 'banned');
exception when duplicate_object then null; end $$;

do $$ begin
  create type "SubdomainStatus" as enum ('active', 'suspended');
exception when duplicate_object then null; end $$;

do $$ begin
  create type "AbuseReportStatus" as enum ('open', 'resolved', 'ignored');
exception when duplicate_object then null; end $$;

-- Tables
create table if not exists "User" (
  "id" text primary key,
  "clerkUserId" text not null unique,
  "email" text not null unique,
  "username" text not null unique,
  "role" "UserRole" not null default 'user',
  "status" "UserStatus" not null default 'active',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists "Subdomain" (
  "id" text primary key,
  "userId" text not null,
  "label" text not null,
  "baseFqdn" text not null unique,
  "status" "SubdomainStatus" not null default 'active',
  "riskScore" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint "Subdomain_userId_fkey"
    foreign key ("userId") references "User"("id") on delete cascade
);
create index if not exists "Subdomain_userId_idx" on "Subdomain" ("userId");
create index if not exists "Subdomain_baseFqdn_idx" on "Subdomain" ("baseFqdn");

-- Admin-reserved labels (prevents public claiming)
create table if not exists public."ReservedSubdomain" (
  "id" text primary key,
  "label" text not null,
  "baseFqdn" text not null unique,
  "note" text null,
  "reservedForUserId" text null,
  "createdAt" timestamptz not null default now(),
  "createdByUserId" text null,
  constraint "ReservedSubdomain_reservedForUserId_fkey"
    foreign key ("reservedForUserId") references "User"("id") on delete set null,
  constraint "ReservedSubdomain_createdByUserId_fkey"
    foreign key ("createdByUserId") references "User"("id") on delete set null
);
create index if not exists "ReservedSubdomain_label_idx" on public."ReservedSubdomain" ("label");
create index if not exists "ReservedSubdomain_reservedForUserId_idx" on public."ReservedSubdomain" ("reservedForUserId");

create table if not exists "DnsRecord" (
  "id" text primary key,
  "subdomainId" text not null,
  "cloudflareRecordId" text not null unique,
  "type" text not null,
  "host" text not null,
  "fqdn" text not null,
  "content" text not null,
  "ttl" integer not null,
  "priority" integer null,
  "proxied" boolean null,
  "data" jsonb null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint "DnsRecord_subdomainId_fkey"
    foreign key ("subdomainId") references "Subdomain"("id") on delete cascade
);
create index if not exists "DnsRecord_subdomainId_idx" on "DnsRecord" ("subdomainId");
create index if not exists "DnsRecord_fqdn_idx" on "DnsRecord" ("fqdn");

create table if not exists "DelegatedNameserver" (
  "id" text primary key,
  "subdomainId" text not null,
  "nameserver" text not null,
  "cloudflareRecordId" text not null unique,
  "createdAt" timestamptz not null default now(),
  constraint "DelegatedNameserver_subdomainId_fkey"
    foreign key ("subdomainId") references "Subdomain"("id") on delete cascade
);
create index if not exists "DelegatedNameserver_subdomainId_idx" on "DelegatedNameserver" ("subdomainId");

create table if not exists "AbuseReport" (
  "id" text primary key,
  "domain" text not null,
  "reason" text not null,
  "description" text not null,
  "reporterEmail" text null,
  "status" "AbuseReportStatus" not null default 'open',
  "createdAt" timestamptz not null default now()
);
create index if not exists "AbuseReport_domain_idx" on "AbuseReport" ("domain");
create index if not exists "AbuseReport_status_idx" on "AbuseReport" ("status");

create table if not exists "AuditLog" (
  "id" text primary key,
  "actorUserId" text null,
  "action" text not null,
  "targetType" text not null,
  "targetId" text null,
  "metadata" jsonb null,
  "timestamp" timestamptz not null default now(),
  constraint "AuditLog_actorUserId_fkey"
    foreign key ("actorUserId") references "User"("id") on delete set null
);
create index if not exists "AuditLog_actorUserId_idx" on "AuditLog" ("actorUserId");
create index if not exists "AuditLog_timestamp_idx" on "AuditLog" ("timestamp");
create index if not exists "AuditLog_action_idx" on "AuditLog" ("action");

-- System settings (simple key/value config)
create table if not exists public."SystemSetting" (
  "key" text primary key,
  "value" jsonb not null,
  "updatedAt" timestamptz not null default now(),
  "updatedByUserId" text null,
  constraint "SystemSetting_updatedByUserId_fkey"
    foreign key ("updatedByUserId") references "User"("id") on delete set null
);
create index if not exists "SystemSetting_updatedAt_idx" on public."SystemSetting" ("updatedAt");

-- Admin announcements (maintenance, incidents, updates)
create table if not exists public."Announcement" (
  "id" text primary key,
  "title" text not null,
  "body" text not null,
  "level" text not null default 'info', -- info|warn|danger
  "published" boolean not null default false,
  "startsAt" timestamptz not null default now(),
  "endsAt" timestamptz null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "createdByUserId" text null,
  "updatedByUserId" text null,
  constraint "Announcement_createdByUserId_fkey"
    foreign key ("createdByUserId") references "User"("id") on delete set null,
  constraint "Announcement_updatedByUserId_fkey"
    foreign key ("updatedByUserId") references "User"("id") on delete set null
);
create index if not exists "Announcement_published_idx" on public."Announcement" ("published");
create index if not exists "Announcement_startsAt_idx" on public."Announcement" ("startsAt");
create index if not exists "Announcement_endsAt_idx" on public."Announcement" ("endsAt");

-- Short Links (Short.io integration)
create table if not exists "ShortLink" (
  "id" text primary key,
  "userId" text not null,
  "originalUrl" text not null,
  "shortSlug" text not null unique,
  "shortUrl" text not null,
  "shortioLinkId" text not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint "ShortLink_userId_fkey"
    foreign key ("userId") references "User"("id") on delete cascade
);
create index if not exists "ShortLink_userId_idx" on "ShortLink" ("userId");
create index if not exists "ShortLink_shortSlug_idx" on "ShortLink" ("shortSlug");

-- API Keys (DDNS tokens)
create table if not exists "ApiKey" (
  "id" text primary key,
  "userId" text not null,
  "key" text not null unique,
  "name" text not null,
  "createdAt" timestamptz not null default now(),
  "lastUsedAt" timestamptz null,
  constraint "ApiKey_userId_fkey"
    foreign key ("userId") references "User"("id") on delete cascade
);
create index if not exists "ApiKey_userId_idx" on "ApiKey" ("userId");
create index if not exists "ApiKey_key_idx" on "ApiKey" ("key");
